ActionController::Routing::Routes.draw do |map|
  map.resources :photos

  map.resources :taggings

  map.resources :tags

  map.resources :geocodings

  map.resources :geocodes

  map.resources :users

  map.resources :images

  map.resources :stories

  map.resources :venues

  map.resources :ratings

  map.resources :locations

  map.resources :comments

  map.resources :votes

  map.resources :content_images

  map.resources :schema_migrations

  map.resources :photos

  map.resources :users

  map.resources :images

  map.resources :stories

  map.resources :venues

  map.resources :ratings

  map.resources :locations

  map.resources :comments

  map.resources :votes

  map.resources :content_images

  map.resources :schema_migrations

  map.resources :schema_migrations

  map.resources :guides

  map.resources :users do |users|
    users.resources :locations
  end

  map.resources :venues do |venues|
    venues.resources :locations
  end

  map.resources :stories do |stories|
    stories.resources :comments
    stories.resources :ratings
    stories.resources :locations
  end

  map.resources :ratings

  map.resources :content_images


  # The priority is based upon order of creation: first created -> highest priority.

  # Sample of regular route:
  #   map.connect 'products/:id', :controller => 'catalog', :action => 'view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   map.purchase 'products/:id/purchase', :controller => 'catalog', :action => 'purchase'
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   map.resources :products

  # Sample resource route with options:
  #   map.resources :products, :member => { :short => :get, :toggle => :post }, :collection => { :sold => :get }

  # Sample resource route with sub-resources:
  #   map.resources :products, :has_many => [ :comments, :sales ], :has_one => :seller
  
  # Sample resource route with more complex sub-resources
  #   map.resources :products do |products|
  #     products.resources :comments
  #     products.resources :sales, :collection => { :recent => :get }
  #   end

  # Sample resource route within a namespace:
  #   map.namespace :admin do |admin|
  #     # Directs /admin/products/* to Admin::ProductsController (app/controllers/admin/products_controller.rb)
  #     admin.resources :products
  #   end

  # You can have the root of your site routed with map.root -- just remember to delete public/index2.html.
  # map.root :controller => "welcome"

  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing or commenting them out if you're using named routes and resources.
  
  map.connect "destinations/:locale/:season",
              :controller => "guides",
              :action => "show_locale",
              :locale => nil,
              :season => nil

  map.connect "adventures/:activity/:locale/:season",
              :controller => "guides",
              :action => "show_activity",
              :activity =>nil,
              :locale => nil,
              :season => nil

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

######## List of Routs (generated by Rake) Follow
#             guides GET    /guides(.:format)                               {:controller=>"guides", :action=>"index"}
#                    POST   /guides(.:format)                               {:controller=>"guides", :action=>"create"}
#          new_guide GET    /guides/new(.:format)                           {:controller=>"guides", :action=>"new"}
#         edit_guide GET    /guides/:id/edit(.:format)                      {:controller=>"guides", :action=>"edit"}
#              guide GET    /guides/:id(.:format)                           {:controller=>"guides", :action=>"show"}
#                    PUT    /guides/:id(.:format)                           {:controller=>"guides", :action=>"update"}
#                    DELETE /guides/:id(.:format)                           {:controller=>"guides", :action=>"destroy"}
#     user_locations GET    /users/:user_id/locations(.:format)             {:controller=>"locations", :action=>"index"}
#                    POST   /users/:user_id/locations(.:format)             {:controller=>"locations", :action=>"create"}
#  new_user_location GET    /users/:user_id/locations/new(.:format)         {:controller=>"locations", :action=>"new"}
# edit_user_location GET    /users/:user_id/locations/:id/edit(.:format)    {:controller=>"locations", :action=>"edit"}
#      user_location GET    /users/:user_id/locations/:id(.:format)         {:controller=>"locations", :action=>"show"}
#                    PUT    /users/:user_id/locations/:id(.:format)         {:controller=>"locations", :action=>"update"}
#                    DELETE /users/:user_id/locations/:id(.:format)         {:controller=>"locations", :action=>"destroy"}
#              users GET    /users(.:format)                                {:controller=>"users", :action=>"index"}
#                    POST   /users(.:format)                                {:controller=>"users", :action=>"create"}
#           new_user GET    /users/new(.:format)                            {:controller=>"users", :action=>"new"}
#          edit_user GET    /users/:id/edit(.:format)                       {:controller=>"users", :action=>"edit"}
#               user GET    /users/:id(.:format)                            {:controller=>"users", :action=>"show"}
#                    PUT    /users/:id(.:format)                            {:controller=>"users", :action=>"update"}
#                    DELETE /users/:id(.:format)                            {:controller=>"users", :action=>"destroy"}
#    venue_locations GET    /venues/:venue_id/locations(.:format)           {:controller=>"locations", :action=>"index"}
#                    POST   /venues/:venue_id/locations(.:format)           {:controller=>"locations", :action=>"create"}
# new_venue_location GET    /venues/:venue_id/locations/new(.:format)       {:controller=>"locations", :action=>"new"}
#edit_venue_location GET    /venues/:venue_id/locations/:id/edit(.:format)  {:controller=>"locations", :action=>"edit"}
#     venue_location GET    /venues/:venue_id/locations/:id(.:format)       {:controller=>"locations", :action=>"show"}
#                    PUT    /venues/:venue_id/locations/:id(.:format)       {:controller=>"locations", :action=>"update"}
#                    DELETE /venues/:venue_id/locations/:id(.:format)       {:controller=>"locations", :action=>"destroy"}
#             venues GET    /venues(.:format)                               {:controller=>"venues", :action=>"index"}
#                    POST   /venues(.:format)                               {:controller=>"venues", :action=>"create"}
#          new_venue GET    /venues/new(.:format)                           {:controller=>"venues", :action=>"new"}
#         edit_venue GET    /venues/:id/edit(.:format)                      {:controller=>"venues", :action=>"edit"}
#              venue GET    /venues/:id(.:format)                           {:controller=>"venues", :action=>"show"}
#                    PUT    /venues/:id(.:format)                           {:controller=>"venues", :action=>"update"}
#                    DELETE /venues/:id(.:format)                           {:controller=>"venues", :action=>"destroy"}
#     story_comments GET    /stories/:story_id/comments(.:format)           {:controller=>"comments", :action=>"index"}
#                    POST   /stories/:story_id/comments(.:format)           {:controller=>"comments", :action=>"create"}
#  new_story_comment GET    /stories/:story_id/comments/new(.:format)       {:controller=>"comments", :action=>"new"}
# edit_story_comment GET    /stories/:story_id/comments/:id/edit(.:format)  {:controller=>"comments", :action=>"edit"}
#      story_comment GET    /stories/:story_id/comments/:id(.:format)       {:controller=>"comments", :action=>"show"}
#                    PUT    /stories/:story_id/comments/:id(.:format)       {:controller=>"comments", :action=>"update"}
#                    DELETE /stories/:story_id/comments/:id(.:format)       {:controller=>"comments", :action=>"destroy"}
#      story_ratings GET    /stories/:story_id/ratings(.:format)            {:controller=>"ratings", :action=>"index"}
#                    POST   /stories/:story_id/ratings(.:format)            {:controller=>"ratings", :action=>"create"}
#   new_story_rating GET    /stories/:story_id/ratings/new(.:format)        {:controller=>"ratings", :action=>"new"}
#  edit_story_rating GET    /stories/:story_id/ratings/:id/edit(.:format)   {:controller=>"ratings", :action=>"edit"}
#       story_rating GET    /stories/:story_id/ratings/:id(.:format)        {:controller=>"ratings", :action=>"show"}
#                    PUT    /stories/:story_id/ratings/:id(.:format)        {:controller=>"ratings", :action=>"update"}
#                    DELETE /stories/:story_id/ratings/:id(.:format)        {:controller=>"ratings", :action=>"destroy"}
#    story_locations GET    /stories/:story_id/locations(.:format)          {:controller=>"locations", :action=>"index"}
#                    POST   /stories/:story_id/locations(.:format)          {:controller=>"locations", :action=>"create"}
# new_story_location GET    /stories/:story_id/locations/new(.:format)      {:controller=>"locations", :action=>"new"}
#edit_story_location GET    /stories/:story_id/locations/:id/edit(.:format) {:controller=>"locations", :action=>"edit"}
#     story_location GET    /stories/:story_id/locations/:id(.:format)      {:controller=>"locations", :action=>"show"}
#                    PUT    /stories/:story_id/locations/:id(.:format)      {:controller=>"locations", :action=>"update"}
#                    DELETE /stories/:story_id/locations/:id(.:format)      {:controller=>"locations", :action=>"destroy"}
#            stories GET    /stories(.:format)                              {:controller=>"stories", :action=>"index"}
#                    POST   /stories(.:format)                              {:controller=>"stories", :action=>"create"}
#          new_story GET    /stories/new(.:format)                          {:controller=>"stories", :action=>"new"}
#         edit_story GET    /stories/:id/edit(.:format)                     {:controller=>"stories", :action=>"edit"}
#              story GET    /stories/:id(.:format)                          {:controller=>"stories", :action=>"show"}
#                    PUT    /stories/:id(.:format)                          {:controller=>"stories", :action=>"update"}
#                    DELETE /stories/:id(.:format)                          {:controller=>"stories", :action=>"destroy"}
#            ratings GET    /ratings(.:format)                              {:controller=>"ratings", :action=>"index"}
#                    POST   /ratings(.:format)                              {:controller=>"ratings", :action=>"create"}
#         new_rating GET    /ratings/new(.:format)                          {:controller=>"ratings", :action=>"new"}
#        edit_rating GET    /ratings/:id/edit(.:format)                     {:controller=>"ratings", :action=>"edit"}
#             rating GET    /ratings/:id(.:format)                          {:controller=>"ratings", :action=>"show"}
#                    PUT    /ratings/:id(.:format)                          {:controller=>"ratings", :action=>"update"}
#                    DELETE /ratings/:id(.:format)                          {:controller=>"ratings", :action=>"destroy"}
#     content_images GET    /content_images(.:format)                       {:controller=>"content_images", :action=>"index"}
#                    POST   /content_images(.:format)                       {:controller=>"content_images", :action=>"create"}
#  new_content_image GET    /content_images/new(.:format)                   {:controller=>"content_images", :action=>"new"}
# edit_content_image GET    /content_images/:id/edit(.:format)              {:controller=>"content_images", :action=>"edit"}
#      content_image GET    /content_images/:id(.:format)                   {:controller=>"content_images", :action=>"show"}
#                    PUT    /content_images/:id(.:format)                   {:controller=>"content_images", :action=>"update"}
#                    DELETE /content_images/:id(.:format)                   {:controller=>"content_images", :action=>"destroy"}
#                           /destinations/:locale/:season                   {:controller=>"guides", :action=>"show_locale"}
#                           /adventures/:activity/:locale/:season           {:controller=>"guides", :action=>"show_activity"}
#                           /:controller/:action/:id
#                           /:controller/:action/:id(.:format)